### ISSUE TITLE
Connect 2 device to play Multiplayer

### ISSUE THREAD

**Issue by lcdlv** [hishriTaha/UE-Bluetooth-Support#4]
Hi! There is a way to do like a local network and play multiplayer?

**Comment by tahaHichri** [comment]
Hey there.
Not as of yet. The next update will add changes made on nearby devices characteristics.
That way your app will be aware about changes made on connected devices.

**Comment by lcdlv** [comment]
Cool, will be great can play via bluetooth!

**Comment by lcdlv** [comment]
I´m in a trouble with Online subsystems... maybe you know about that.
When Online subsytem Google Play is working, and my game is logged into Play Service, I can´t create or find session to play on LAN, but works if I do a manual connection using console (open map listen, and open IP). The problem with console is I need to get the IP of device runs as server, and this is very complicated to get on android. A normal user cannot get this IP from setting, device state.... etc.
I think I have two choices: Make some C++ code to get the local IP of the device and the user tell the server IP to his friend to join.
Second choice, make some C++ code to shutdown Google Play Subsystem and init Null Online Subsystem.... on runtime.
Do you have any idea about that? I´m desperate, I had my game working, but I need this final step.

**Comment by lcdlv** [comment]
Hi had this code to get the local IP, works only in PC, in Android gives 127.0.0.1

FString AIPPlayerController::GetIP() {
    bool canBind = false;
    TSharedRef<FInternetAddr> localIp = ISocketSubsystem::Get(PLATFORM_SOCKETSUBSYSTEM)->GetLocalHostAddr(*GLog, canBind);
    return (localIp->IsValid() ? localIp->ToString(false) : "");
}

**Comment by tahaHichri** [comment]
Hello again.. I am sorry cannot help you with that :)
